# -*- coding: utf-8 -*-
"""CMlab_PCA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1De_1h2vLyMJI99j45lJdHE9QYq9940pI
"""

from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt
from skimage import io, color, img_as_float
from sklearn.decomposition import PCA
from pathlib import Path


IMAGES_DIR = "/sample_data/images_grayscale"
IMAGE_EXT = "*.jpg.chip.jpg"
CONVERT_TO_GRAYSCALE = True
N_PC_TO_SHOW = 5
VARIANCE_THRESHOLD = 0.90

try:
    import google.colab
    IN_COLAB = True
except ImportError:
    IN_COLAB = False

if IN_COLAB:

  import zipfile
  with zipfile.ZipFile("/content/sample_data/images_grayscale.zip", "r") as z:
    z.extractall("/content/sample_data/images_grayscale")

    IMAGES_PATH = Path("/content/sample_data/images_grayscale")

  try:
      BASE_DIR = Path(__file__).resolve().parent
  except NameError:
      BASE_DIR = Path.cwd()

else:
    try:
        BASE_DIR = Path(__file__).resolve().parent
    except NameError:
        BASE_DIR = Path.cwd()
    IMAGES_PATH = BASE_DIR / "images_grayscale"

# ----------------------------------------------------------------------
# 1. CARICAMENTO DELLE IMMAGINI
# ----------------------------------------------------------------------
def load_images(images_path: Path, ext: str, grayscale: bool):
    filepaths = sorted(images_path.glob(ext))
    if not filepaths:
        raise FileNotFoundError(
            f"Nessuna immagine trovata in {images_path} con estensione {ext}. "
            "Controlla IMAGES_DIR e IMAGE_EXT."
        )

    images = []
    for fp in filepaths:
        img = img_as_float(io.imread(fp))  # valori in [0, 1]
        if grayscale and img.ndim == 3:
            img = color.rgb2gray(img)
        images.append(img)

    shapes = {img.shape for img in images}
    if len(shapes) > 1:
        raise ValueError(
            f"Le immagini hanno shape diverse: {shapes}. "
            "Devono avere tutte le stesse dimensioni prima della PCA "
            "(ridimensionale con skimage.transform.resize se necessario)."
        )

    img_shape = images[0].shape
    X = np.array([img.flatten() for img in images])  # shape (n, p)
    return X, img_shape, filepaths


print("Caricamento immagini...")
X, img_shape, filepaths = load_images(IMAGES_PATH, IMAGE_EXT, CONVERT_TO_GRAYSCALE)
n, p = X.shape
print(f"Caricate {n} immagini, ciascuna con shape {img_shape} -> vettori di dimensione {p}")

# ----------------------------------------------------------------------
# 2. PCA
# ----------------------------------------------------------------------
mean_image = X.mean(axis=0)
X_centered = X - mean_image

pca = PCA()
scores = pca.fit_transform(X_centered)          # (n, n_components) -> predittori per il modello di encoding
components = pca.components_                    # (n_components, p)
explained_var_ratio = pca.explained_variance_ratio_
cum_var = np.cumsum(explained_var_ratio)

n_components_selected = int(np.searchsorted(cum_var, VARIANCE_THRESHOLD) + 1)
print(f"Numero di PC necessarie per spiegare almeno il {VARIANCE_THRESHOLD:.0%} "
      f"della varianza: {n_components_selected} (su un massimo di {len(explained_var_ratio)})")

# ----------------------------------------------------------------------
# 3. VISUALIZZAZIONE DELLE PRIME COMPONENTI (min score / media / max score)
# ----------------------------------------------------------------------
def show_pc_effect(pc_idx, scores, components, mean_image, img_shape, grayscale):
    s_min = scores[:, pc_idx].min()
    s_max = scores[:, pc_idx].max()
    v = components[pc_idx]

    img_min = (mean_image + s_min * v).reshape(img_shape)
    img_avg = mean_image.reshape(img_shape)
    img_max = (mean_image + s_max * v).reshape(img_shape)

    fig, axes = plt.subplots(1, 3, figsize=(9, 3))
    cmap = "gray" if grayscale else None
    for ax, im, title in zip(axes, [img_min, img_avg, img_max],
                              ["min score", "media", "max score"]):
        ax.imshow(np.clip(im, 0, 1), cmap=cmap)
        ax.set_title(title)
        ax.axis("off")
    fig.suptitle(f"PC {pc_idx + 1} "
                 f"(varianza spiegata: {explained_var_ratio[pc_idx]:.2%})")
    fig.tight_layout()
    return fig

print("Generazione figure per le prime componenti...")
for i in range(N_PC_TO_SHOW):
    fig = show_pc_effect(i, scores, components, mean_image, img_shape, CONVERT_TO_GRAYSCALE)
    fig.savefig(BASE_DIR / f"pc_{i + 1}_effect.png", dpi=150)
plt.show()

# ----------------------------------------------------------------------
# 5. BAR PLOT DELLA VARIANZA SPIEGATA
# ----------------------------------------------------------------------
fig, ax = plt.subplots(figsize=(8, 4))
ax.bar(range(1, len(explained_var_ratio) + 1), explained_var_ratio)
ax.set_xlabel("Componente principale")
ax.set_ylabel("Proporzione di varianza spiegata")
ax.set_title("Scree plot")
fig.tight_layout()
fig.savefig(BASE_DIR / "scree_plot.png", dpi=150)
plt.show()

fig, ax = plt.subplots(figsize=(8, 4))
ax.plot(range(1, len(cum_var) + 1), cum_var, marker="o", markersize=3)
ax.axhline(VARIANCE_THRESHOLD, color="red", linestyle="--",
           label=f"soglia {VARIANCE_THRESHOLD:.0%}")
ax.axvline(n_components_selected, color="gray", linestyle=":")
ax.set_xlabel("Numero di componenti")
ax.set_ylabel("Varianza cumulata spiegata")
ax.set_title("Varianza cumulata")
ax.legend()
fig.tight_layout()
fig.savefig(BASE_DIR / "cumulative_variance_plot.png", dpi=150)
plt.show()

# ----------------------------------------------------------------------
# 6. PREDITTORI PER IL MODELLO DI ENCODING
# ----------------------------------------------------------------------
# scores[:, :n_components_selected] sono i predittori (X) da usare nel
# modello di encoding lineare che mette in relazione lo spazio PCA con
# il rating/target. Salvati qui per il passo successivo dell'assignment.

encoding_predictors = scores[:, :n_components_selected]
np.save(BASE_DIR / "pca_scores_selected.npy", encoding_predictors)
print(f"Salvati {encoding_predictors.shape[1]} predittori PCA per {n} immagini "
      f"in pca_scores_selected.npy")